version: '3'

services:

  php:
    container_name: test-websocket-php
    image: ghcr.io/ld-web/php-apache:8.2
    volumes:
      - ./html:/var/www/html/
    ports:
      - '80:80'
      - '8090:8090'